name: sliver_app_bar_builder
description: A truly customizable sliver for app bars with the benefit of using builders.
version: 1.0.2
repository: https://github.com/netglade/sliver_app_bar_builder
issue_tracker: https://github.com/netglade/sliver_app_bar_builder/issues

environment:
  sdk: '>=2.18.5 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  dart_code_metrics: ^5.5.1
  flutter_test:
    sdk: flutter
  netglade_analysis: 1.1.2
