name: sliver_app_bar_builder
description: A truly customizable sliver for app bars with the benefit of using builders.
version: 1.1.0
repository: https://github.com/netglade/sliver_app_bar_builder
issue_tracker: https://github.com/netglade/sliver_app_bar_builder/issues
screenshots:
  - description: The sliver_app_bar_builder package logo.
    path: doc/icon.png

environment:
  sdk: ">=2.18.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  netglade_analysis: ^5.0.0
