name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0

      - name: Install Dependencies
        run: flutter pub get

      - name: Format
        run: dart format --line-length 120 --set-exit-if-changed .

      - name: Flutter Analyze
        run: flutter analyze --no-pub --fatal-infos --fatal-warnings

      - name: Dart Code Metrics Analyze
        run: flutter pub run dart_code_metrics:metrics analyze lib test --fatal-style --fatal-performance --fatal-warnings

      - name: Test
        run: flutter test --no-pub --test-randomize-ordering-seed random

      - name: Dry Publish
        run: dart pub publish --dry-run
