name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0

      - name: Install Dependencies
        run: flutter pub get

      - name: Format
        run: dart format --line-length 120 --set-exit-if-changed .

      - name: Flutter Analyze
        run: flutter analyze --no-pub --fatal-infos --fatal-warnings

      - name: Install DCM
        uses: CQLabs/setup-dcm@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run DCM
        uses: CQLabs/dcm-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ci_key: ${{ secrets.DCM_KEY }}
          email: ${{ secrets.DCM_EMAIL }}
          folders: .
          fatal_style: true
          fatal_performance: true
          fatal_warnings: true

      - name: Test
        run: flutter test --no-pub --test-randomize-ordering-seed random

      - name: Dry Publish
        run: dart pub publish --dry-run
